export const appRoutes = {
  appEmail: "/app/email",
  appGenerate: "/app/generate",
  appGrowth: "/app/growth",
  appResult: "/app/result",
  appRoot: "/app",
  appOutreach: "/app/outreach",
  admin: "/admin",
  adminFeatures: "/admin/features",
  adminOutreach: "/admin/outreach",
  adminUsers: "/admin/users",
  adminUsage: "/admin/usage",
  adminWorkspaces: "/admin/workspaces",
  dashboard: "/app/dashboard",
  dashboardAnalytics: "/dashboard/analytics",
  emailCampaigns: "/app/email",
  founderContentIdeas: "/founder-content-ideas",
  linkedinHookGenerator: "/linkedin-hook-generator",
  linkedinPostGenerator: "/linkedin-post-generator",
  linkedinPostIdeasForFounders: "/linkedin-post-ideas-for-founders",
  login: "/login",
  onboarding: "/onboarding",
  settingsPreferences: "/settings/preferences",
  signup: "/signup",
} as const;
